name: publish
on:
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: nuget-publish
  cancel-in-progress: false
jobs:
  validate:
    uses: ./.github/workflows/validate.yml
    with:
      deep: true
  publish:
    needs: validate
    runs-on: windows-2022
    environment: nuget
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - uses: actions/download-artifact@v4
        with:
          name: packages
          path: artifacts/packages
      - uses: NuGet/login@v1
        id: login
        with:
          user: ${{ vars.NUGET_USER }}
      - run: dotnet nuget push artifacts/packages/*.nupkg --api-key "$env:NUGET_API_KEY" --source https://api.nuget.org/v3/index.json
        shell: pwsh
        env:
          NUGET_API_KEY: ${{ steps.login.outputs.NUGET_API_KEY }}
