name: publish
on:
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
jobs:
  publish:
    runs-on: windows-latest
    environment: nuget
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.98.1
      - run: ./scripts/Build.ps1 -Test -Pack
        shell: pwsh
      - uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
      - run: dotnet nuget push artifacts/packages/*.nupkg --api-key '${{ steps.login.outputs.NUGET_API_KEY }}' --source https://api.nuget.org/v3/index.json
        shell: pwsh
